name = "SatelliteToolbox"
uuid = "6ac157d9-b43d-51bb-8fab-48bf53814f4a"
license = "MIT"
desc = "A toolbox for satellite analysis"
authors = ["Ronan Arraes Jardim Chagas <ronisbr@gmail.com>"]
version = "0.10.0"

[deps]
Crayons = "a8cc5b0e-0ffa-5ad4-8c14-923d3ee1735f"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
OptionalData = "fbd9d27c-2d1c-5c1c-99f2-7497d746985d"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
PolynomialRoots = "3a141323-8675-5d76-9d11-e1df1406c778"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
ReferenceFrameRotations = "74f56ac7-18b3-5285-802d-d4bd4f104033"
RemoteFiles = "cbe49d4c-5af1-5b60-bb70-0a60aa018e1b"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
Crayons = "4.0"
Interpolations = "0.14"
OptionalData = "0.3, 1"
Parameters = "0.12"
PolynomialRoots = "1"
PrettyTables = "0.12, 1, 2"
Reexport = "1"
ReferenceFrameRotations = "3"
RemoteFiles = "0.4.2, 0.5"
StaticArrays = "1"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
